name: Build & Test with Bun

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout 
          uses: actions/checkout@v3 # Checkout repo

        - uses: actions/setup-java@v4 # Setup Java 17
          with:
            distribution: 'temurin'
            java-version: '17'

        - name: Setup Bun
          uses: oven-sh/setup-bun@v1 # Setup bun
          with:
            bun-version: latest

        - run: bun i # Install dependencies
        - run: bun run build # Build sources
        - run: bun test --timeout 45000 # Run tests